apiVersion: charts.helm.k8s.io/v1alpha1
kind: AppsodyApp
metadata:
  name: example-appsodyapp
spec:
  # Default values copied from <project_dir>/helm-charts/appsody-app/values.yaml
  
  ###############################################################################
  # Licensed Materials - Property of IBM.
  # Copyright IBM Corporation 2018. All Rights Reserved.
  # U.S. Government Users Restricted Rights - Use, duplication or disclosure
  # restricted by GSA ADP Schedule Contract with IBM Corp.
  #
  # Contributors:
  #  IBM Corporation - initial API and implementation
  ###############################################################################
  
  
  ###############################################################################
  ## Common image variables
  ###############################################################################
  image: {}
    ## Example
    # repository: appsody/appsody-example
    # tag: 0.0.1
    # pullPolicy: Always
    # pullSecrets: []
    # extraEnvs: []
    #   Example:
    #   extraEnvs:
    #   - name: FOO
    #     valueFrom:
    #       secretKeyRef:
    #         key: FOO
    #         name: secret-resource
    #   - name: BAR
    #     value: bar
  
    # extraVolumeMounts: []
    ##   Example:
    #   extraVolumeMounts:
    #     - name: podinfo
    #       mountPath: /podinfo
    #       readOnly: false
  
    # security: {}
    ##   Example:
    #   security:
    #     securityContext:
    #       privileged: false
    #       readOnlyRootFilesystem: false
    #       allowPrivilegeEscalation: false
    #       capabilities:
    #         drop:
    #         - ALL
  
  deployment:
    annotations: {}
    # Example:
    # annotations:
    #   prometheus.io/scheme: "http"
    #   prometheus.io/scrape: "true"
  
    labels: {}
    # Example:
    # labels:
    #   environment: "dev"
    #   tier: "backend"
  
  pod:
    annotations: {}
    # Example:
    # annotations:
    #   prometheus.io/scheme: "http"
    #   prometheus.io/scrape: "true"
  
    security: {}
    # Example:
    # security:
    #   hostNetwork: false
    #   hostPID: false
    #   hostIPC: false
    #   securityContext:
    #     runAsNonRoot: true
    #     runAsUser: 1001
  
    labels: {}
    # Example:
    # labels:
    #   environment: "dev"
    #   tier: "backend"
  
    extraVolumes: []
    # Example:
    # extraVolumes:
    #   - name: podinfo
    #     downwardAPI:
    #       items:
    #         - path: "labels"
    #           fieldRef:
    #             fieldPath: metadata.labels
    #         - path: "annotations"
    #           fieldRef:
    #             fieldPath: metadata.annotations
  
  
  ###############################################################################
  ## Service
  ###############################################################################
  service:
    type: NodePort
    name: http-appsody-app 
    port: 8080
    targetPort: 8080
    labels: {}
    annotations: {}
  
  ###############################################################################
  ## Ingress
  ###############################################################################
  ingress:
    enabled: false
    rewriteTarget: "/"
    path: "/"
    labels: {}
    annotations: {}
    hosts: []
    secretName: ""
    
  ###############################################################################
  ## Configuration Properties
  ###############################################################################
  configProperties:
    configMapName: ""
  
  ###############################################################################
  ## Readiness Probe
  ###############################################################################
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 5
    httpGet:
      enabled: false
      path: "/health"
  
  ###############################################################################
  ## Liveness Probe
  ###############################################################################
  livenessProbe:
    initialDelaySeconds: 180
    periodSeconds: 20
    httpGet:
      enabled: false
      path: "/health"
  
  ###############################################################################
  ## Auto scaling
  ###############################################################################
  replicaCount: 1
  
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
    
  ###############################################################################
  ## Resource constraints
  ###############################################################################
  resources:
    constraints: 
      enabled: false
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 500m
      memory: 10Gi
  
  ###############################################################################
  ## Architecture
  ###############################################################################
  # Specify architecture (amd64, ppc64le, s390x) and weight to be
  # used for scheduling as follows : 
  #   0 - Do not use
  #   1 - Least preferred
  #   2 - No preference
  #   3 - Most preferred
  arch:
    amd64: "3 - Most preferred"
  
  ###############################################################################
  ## Persistence Storage
  ###############################################################################
  
  ## Persistence is disabled by default, set Enabled: true to use
  persistence:
    name: "pvc"
    size: "1Gi"
  
    fsGroupGid: 
  
    useDynamicProvisioning: true
  
    ## Specify the name of the StorageClass
    ## Setting StorageClass: "" will use whatever storageClass is currently
    ## setup as the Default
    storageClassName: "" 
  
    # if your not using dynamic provisioning, you can use selectors to 
    # refine the binding process. You cannot specify a selector if your using dynamic provisioning!
    selector:
      label: ""
      value: ""
  
  ###############################################################################
  ## Logs
  ###############################################################################
  logs:
    persistLogs: false
  
