apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appsodyapps.charts.helm.k8s.io
spec:
  group: charts.helm.k8s.io
  names:
    kind: AppsodyApp
    listKind: AppsodyAppList
    plural: appsodyapps
    singular: appsodyapp
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
