{{- if .Values.replicaCount }}
{{- $stateful := .Values.logs.persistLogs -}}
{{ if $stateful }}
apiVersion: apps/v1
kind: StatefulSet
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: {{ template "appsody.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "appsody.fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- with .Values.deployment.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.deployment.annotations }}
  annotations:
{{ toYaml . | indent 4}}
{{- end }}   
spec:
  {{- if $stateful }}
  serviceName: {{ template "appsody.fullname" . }}
  {{- end }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ template "appsody.fullname" . }}
  template:
    metadata:
      labels:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app: {{ template "appsody.fullname" . }}
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
{{- with .Values.pod.labels }}
{{ toYaml . | indent 8 }}
{{- end }}        
      annotations:
        productName: Appsody Sample Application
        productID: Appsody_Sample_Application_1.0.0_perpetual_00000
        productVersion: 1.0.0
{{- with .Values.pod.annotations }}
{{ toYaml . | indent 8 }}
{{- end }}        
    spec:
      {{- if or .Values.configProperties.configMapName .Values.pod.extraVolumes }}
      volumes:
      {{- if .Values.configProperties.configMapName }}
      - name: config-properties
        configMap:
          name: {{ .Values.configProperties.configMapName }}
      {{- end }}
{{- with .Values.pod.extraVolumes }}
{{ toYaml . | indent 6 }}
{{- end -}}
      {{- end }}
      serviceAccountName: {{ template "appsody.fullname" . }}-sa
      affinity:
      {{- include "appsody.nodeaffinity" . | indent 6 }}
      {{/* Prefer horizontal scaling */}}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "appsody.fullname" . }}
                - key: release
                  operator: In
                  values:
                  - {{ .Release.Name | quote }}
              topologyKey: kubernetes.io/hostname
{{- with .Values.pod.security }}
{{ toYaml . | indent 6 }}
{{- else }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: {{ .Values.persistence.fsGroupGid }}
{{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- with .Values.image.security }}
{{ toYaml . | indent 8 }}
{{- else }}
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
{{- end }}
        readinessProbe:
          {{- if .Values.readinessProbe.httpGet.enabled }}  
          httpGet:
            path: {{ .Values.readinessProbe.httpGet.path }}
            port: {{ .Values.service.targetPort }}
            scheme: HTTPS
          {{- else }}
          tcpSocket:
            port: {{ .Values.service.targetPort }}
          {{- end }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
        livenessProbe:
          {{- if .Values.livenessProbe.httpGet.enabled }}
          httpGet:
            path: {{ .Values.livenessProbe.httpGet.path }}
            port: {{ .Values.service.targetPort }}
            scheme: HTTPS
          {{- else }}
          tcpSocket:
            port: {{ .Values.service.targetPort }}
          {{- end }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
        {{- if or .Values.logs.persistLogs .Values.configProperties.configMapName .Values.image.extraVolumeMounts }}
        volumeMounts:
        {{- if .Values.logs.persistLogs }}
        - mountPath: /logs
          name: {{ .Values.persistence.name | trunc 63 | lower | trimSuffix "-" | quote }}
          subPath: logs
        {{- end }}
        {{- if .Values.configProperties.configMapName }}
        - name: config-properties
          mountPath: /etc/websphere
        {{- end }}
 {{- with .Values.image.extraVolumeMounts }}
{{ toYaml . | indent 8 }}
{{- end -}}         
        {{- end }}
        env:
          - name: PORT
            value: "8080"
{{- if .Values.image.extraEnvs }}
{{ toYaml .Values.image.extraEnvs | indent 8 }}
{{- end }}          
        resources:
          {{- if .Values.resources.constraints.enabled}}      
          limits:
{{ toYaml .Values.resources.limits | indent 12 }}
          requests:
{{ toYaml .Values.resources.requests | indent 12 }}
          {{- end }}
      restartPolicy: "Always"
      terminationGracePeriodSeconds: 30
      dnsPolicy: "ClusterFirst"
  {{ if $stateful -}}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.persistence.name | trunc 63 | lower | trimSuffix "-"  | quote }}
      labels:
        chart: "{{ .Chart.Name }}"
        app: {{ template "appsody.fullname" . }}
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      {{- if .Values.persistence.useDynamicProvisioning }}
      # if present, use the storageClassName from the values.yaml, else use the
      # default storageClass setup by kube Administrator
      # setting storageClassName to nil means use the default storage class
      storageClassName: {{ default nil .Values.persistence.storageClassName | quote }}
      {{- else }}
      # bind to an existing pv.
      # setting storageClassName to "" disables dynamic provisioning
      storageClassName: {{ default "" .Values.persistence.storageClassName | quote }}
      {{- if .Values.persistence.selector.label }}
      # use selectors in the binding process
      selector:
        matchExpressions:
          - {key: {{ .Values.persistence.selector.label }}, operator: In, values: [{{ .Values.persistence.selector.value }}]}
      {{- end }}
      {{- end }}
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
  {{- end }}
{{- end }}  
