
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kitura-clusterrole
rules:
- apiGroups:
  - extensions
  resourceNames:
  - kitura-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use